version: '3.5'

services:

  proxy:
    image: quay.io/oauth2-proxy/oauth2-proxy:v7.2.1
    container_name: oauth2-proxy
    command: --config /oauth2-proxy.cfg
    ports:
      - 4180:4180
      - 443:443
    environment:
      - OAUTH2_PROXY_COOKIE_SECRET=MTExMTExMTExMTExMTExMQ==
    networks:
      - proxy-network
    volumes:
      - ./config/oauth2-proxy.cfg:/oauth2-proxy.cfg
    depends_on:
      - keycloak

  keycloak:
    image: quay.io/keycloak/keycloak:16.1.0
    environment:
      - DB_ADDR=mariadb
      - DB_USER=keycloak
      - DB_PASSWORD=password
    container_name: kc
    volumes:
      - ./keycloak:/tmp/realm-config
    command:
      [
        '-Dkeycloak.migration.action=import',
        '-Dkeycloak.migration.provider=dir',
        '-Dkeycloak.migration.dir=/tmp/realm-config',
        '-Dkeycloak.migration.strategy=IGNORE_EXISTING',
      ]
    networks:
      proxy-network:
        aliases:
          - keycloak.127.0.0.1.nip.io
    ports:
      - 8080:8080
    depends_on:
      - mariadb

  mariadb:
    image: mariadb:10.5.5
    environment:
      - MYSQL_DATABASE=keycloak
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_USER=keycloak
      - MYSQL_PASSWORD=password
    container_name: keycloak-db
    networks:
      - proxy-network
    volumes:
      - vol-mariadb:/var/lib/mysql
    ports:
      - 3306:3306

  server:
    image: kennethreitz/httpbin
    # environment:
    #   - "GUNICORN_CMD_ARGS=\"--capture-output --error-logfile - --access-logfile - --access-logformat \"%(h)s %(t)s %(r)s %(s)s Host: %({Host}i)s}\"\""
    ports:
      - 8000:80
    container_name: server
    networks:
      - proxy-network

  nginx:
    image: nginx:alpine
    ports:
      - 9000:80
    container_name: nginx
    volumes:
      - ./nginx:/etc/nginx/conf.d
    networks:
      - proxy-network
    depends_on:
      - server
      - proxy

networks:
  proxy-network:
    name: local

volumes:
  vol-mariadb:
